# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               '(-:'
tagline:             'Geekerie, logiciel libre et vilain gauchisme'
description:         Gaëtan Lehmann
url:                 http://glehmann.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:           Gaëtan Lehmann
  url:            https://glehmann.net
  email:          gaetan.lehmann@gmail.com
  email_md5:      a5fe9fd140b01eeaaaf78607686fdcf1

# defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: page
      comments: true
      tags: code

# Custom vars
